### ISSUE TITLE
Add logging capability

### ISSUE THREAD

**Issue by AlexLemna** [AlexLemna/rosevomit#27]
Basically, let's explore the `logging` module.
- [x] Let the 'settings-data.ini' file set the log message severity threshold
- [x] Determine a format for the logging messages written to file
- [x] Test that loggers in different modules can, in fact, write to a specified .log file
- [x] Create functional proof-of-concept
- [x] Add logging messages throughout program (see #TODO comments)
- [x] Try out configuring loggers via .yaml or dictionaries
- [x] Add a "how to read this" section at the start of each log file.
- [x] Use a log buffer to capture the "early" init messages
- [x] Add loggers to each file
- [x] See if it is possible to include comments in the auto-generated settings-data.ini file
- [x] Add a timestamp indicating when logging session begins
- [x] Add a "README" explaining how the logging functions work currently, so I can more easily come back to this later and refactor/clean it up

**Comment by AlexLemna** [comment]
Tried configuring loggers via dictionary. It gets complex - I'll probably save it for another day, since so far I can accomplish my goals without using dictionaries.
