### ISSUE TITLE
Add licensing information to program

### ISSUE THREAD

**Issue by AlexLemna** [AlexLemna/rosevomit#47]
- [x] Add strings containing licensing info
- [x] Write programcli module/functions to display the info strings
- [x] Update the appropriate menus to allow calling to info string display module/functions
- [x] Tweak formatting to taste
