### ISSUE TITLE
Improve/refactor logging functionality

### ISSUE THREAD

**Issue by AlexLemna** [AlexLemna/rosevomit#50]
- [ ] Replace the 'debugmessage' function with a logging function
- [ ] Fix the commented-out "debugmessage" snippets in core._dynamic_constants.py
- [ ] Refactor logging function - use filters instead of multiple handlers? (this might allow us to avoid using a single FileHandler for the message buffer)
- [ ] Better formatting for output files (?)
- [ ] Uniform timestamps at the "BEGIN SESSION" lines in the output files (?)
- [ ] Remove the '00-buffer.log' output file and redirect contents to appropriate destinations
- [ ] Add examples to the logdata README
