### ISSUE TITLE
Suncalc refactoring

### ISSUE THREAD

**Issue by AlexLemna** [AlexLemna/rosevomit#54]
- [x] Remove option to save to temp directory - not really necessary for our purposes
- [x] Adjust menu interfaces to reflect changing features
- [x] Move suncalc helper functions to suncalc_helpers.py
